### ISSUE TITLE
Create Book Model

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#1]
## User Story
As a **product owner** I can **see the first version of models** so that **confirm their functionality**.

## Acceptance Criteria
- [x] AC 1 create ERDs
- [x] AC 2 create models and populate models.py
- [x] AC 3 migrate models
- [x] AC 4 test the functionality of the models

## Tasks

- [x] T1 Vladimir :-)
- [x] T2 Vladimir :-) 
- [x] T3 Vladimir :-)
- [x] T4 Vladimir :-)

**Comment by VladaAlek** [comment]
Tasks are not properly defined.
