### ISSUE TITLE
create index- and base html files

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#10]
## User Story
As a **product owner** I can **see two html files** so that **I can testify their functionality**.

## Acceptance Criteria
- [x] AC 1 two html files are created
- [x] AC 2 two html files are validated
- [ ] AC 3
- [ ] AC 4

## Tasks

- [x] T1 create two html files
- [x] T2 validate two html files
- [ ] T3
- [ ] T4

**Comment by VladaAlek** [comment]
**Addition:** add wireframe to Readme.md file

**Addition:** use "block content" to connect two files!

**Comment by VladaAlek** [comment]
Do additional checks why the validator doesn`t accept  as a valid code
