### ISSUE TITLE
Transfer review sources to Readme.md file

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#12]
## User Story
As a **user** I don't **want to see the URL links spill over the viewport in the small-size formats** so that **I have imporved UX**.

## Acceptance Criteria
- [x] AC 1 URL links are deleted from Reviews database
- [x] AC 2  URL links are transferred to Readme.md file 
- [ ] AC 3
- [ ] AC 4

## Tasks

- [x] T1 delete URL links from Reviews database
- [x] T2 transfer URL links to Readme.md file 
- [ ] T3
- [ ] T4
