### ISSUE TITLE
Create About page

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#13]
## User Story
As a **user** I can **find out more about the purpose of entering data into the bibliography** so that **I can  **comprehend its importance and input correct data into the database**.

## Acceptance Criteria
- [x] AC 1 About.html is created on the app level
- [x] AC 2 code for About.html and custom CSS code are created
- [x] AC 3 navigable links are established in base.html navbar
- [x] AC 4 functionality of code is tested and validated

## Tasks

- [x] T1 create About.html 
- [x] T2 write code for About.html and custom CSS
- [x] T3 establish links
- [x] T4 test functionality and validate CSS and HTML codes
