### ISSUE TITLE
USER STORY <OPEN INDIVIDUAL REVIEWS>

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#14]
## User Story
As a **user** I can **open the individual book review on the full page** so that **I can read its content easier**.

## Acceptance Criteria
- [x] AC 1 full view html and custom CSS are created
- [x] AC 2 Django is prepared to facilitate this changes
- [x] AC 3 HTML and CSS are validated
- [x] AC 4 functionality is tested

## Tasks

- [x] T1 create HTML and custom CSS
- [x] T2 adjust Django
- [x] T3 validate HTML and CSS
- [x] T4 test functionality

**Comment by VladaAlek** [comment]
HTML validated, CSS to be done later
