### ISSUE TITLE
USER STORY <ADD FIXTURES>

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#15]
## User Story
As a **superuser** I can **populate the database with the data from the JSON file** so that **avoid entering data manually and save time**.

## Acceptance Criteria
- [x] AC 1 JSON file is created
- [x] AC 2 Fixtures are added to Django
- [ ] AC 3 
- [ ] AC 4

## Tasks

- [x] T1 create JSON file
- [x] T2 add Fixtures to Django
- [ ] T3
- [ ] T4
