### ISSUE TITLE
USER STORY <ADD PAGINATION TO REVIEWS>

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#16]
## User Story
As a **superuser** I can **determine the number of reviews on one page** so that **user have better overlook and an option to navigate through the conntent**.

## Acceptance Criteria
- [x] AC 1 optimal number of reviews is displayed on the screen
- [x] AC 2 "next" and "previous" buttons are introduced
- [x] AC 3 functionality is checked
- [ ] AC 4

## Tasks

- [x] T1 adjust Index.html file
- [x] T2 validate HTML code
- [ ] T3
- [ ] T4

**Comment by VladaAlek** [comment]
**Correction** The pagination feature will be enabled for the bibliographical list. For the review list, scrolling effect provides better UX
