### ISSUE TITLE
EPIC <Account Registration>

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#17]
## User Story
As a **user** I can **register to the site** so that **input book data and leave review**.

## Acceptance Criteria
- [x] AC 1 Allauth is installed
- [x] AC 2 HTML and CSS are created
- [x] AC 3 HTML and CSS is validated
- [x] AC 4 functionality is tested and the project is deployed

## Tasks

- [x] T1 install Allauth
- [x] T2 create static files
- [x] T3 validate HTML and CSS
- [x] T4 test functionality and deploy the project

**Comment by VladaAlek** [comment]
Before closing this card, be sure that you styled the Register Yourself, as it has not been done, yet.
