### ISSUE TITLE
USER STORY <ENABLING REVIEW CREATION >

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#18]
## User Story
As a **user** I can **create a new review** so that **I can express my opinion on certain topics**.

## Acceptance Criteria
- [x] AC 1 logged user can leave the comment
- [x] AC 2 number count for reviews is visible
- [x] AC 3 review_detail.html is extended for the new feature
- [x] AC 4 custom CSS is created
- [x] AC 5 functionality is tested

## Tasks

- [x] T1 refactor views.py and review_detail.html
- [x] T2 create custom CSS
- [x] T3 test functionality and validate code
- [ ] T4
