### ISSUE TITLE
Create Review Model

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#2]
## User Story
As a **product owner** I can **see the Review model** so that **I can confirm its functionality and compatibility with the Book model**.

## Acceptance Criteria
- [x] AC 1 create ERD and add it to Read.me
- [x] AC 2 create model and populate models.py file
- [x] AC 3 test model's functionality
- [ ] AC 4 

## Tasks

- [ ] T1
- [ ] T2
- [ ] T3
- [ ] T4
