### ISSUE TITLE
USER STORY <HANDLE POST METHOD FOR CONTRIBUTE SECTION AT ABOUT PAGE>

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#20]
## User Story
As a **user** I can **enter bibliographical data in the form field in the "About Page"** so that ** I can populate data with my favorite books to be discussed**.

## Acceptance Criteria
- [x] AC 1 forms.py, views.py, urls.py and about.html are refactored
- [x] AC 2 code is validated
- [x] AC 3 code's functionality has been tested
- [ ] AC 4

## Tasks

- [x] T1 refactor forms.py, views.py, urls.py and about.html
- [x] T2 validate code
- [x] T3 test functionality
- [ ] T4

**Comment by VladaAlek** [comment]
Reviewed and accepted.
