### ISSUE TITLE
USER STORY <ADD  UPDATE AND DELETE REVIEW OPTION>

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#21]
## User Story
As a **user** I can **delete and update my own comments** so that ** I can delete or update my posts that are not relevant anymore, or have to be changed for some reason**.

## Acceptance Criteria
- [x] AC 1 Views, URL are updated
- [x] AC 2 edit/delete buttons are added
- [x] AC 3 JS code is written and implemented
- [x] AC 4 code is validated
- [ ] AC 5 functionality of new features is tested 

## Tasks

- [x] T1 update Views, URL
- [x] T2 create edit/delete buttons 
- [x] T3 add and implement JS code 
- [ ] T4 test functionality

**Comment by VladaAlek** [comment]
new class ReviewForm added, too.

**Comment by VladaAlek** [comment]
Testing the code failed.
