### ISSUE TITLE
USER STORY <USER CAN ADD PHOTOS>

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#22]
## User Story
As a **user** I can **load photos** so that **each book title is accompanied by the cover photo**.

## Acceptance Criteria
- [x] AC 1 Cloudinary API is installed 
- [x] AC 2 API is connected to the project
- [x] AC 3 book app is updated
- [x] AC 4 code is validated
- [x] AC 5 functionality is tested

## Tasks

- [x] T1 install and connect Cloudinary API
- [x] T2 update book app
- [x] T3 validate code
- [x] T4 test functionality
