### ISSUE TITLE
EPIC <Implement Read functionality>

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#25]
## User Story
As a **user** I can **see the individual contributions** so that **I can have more details about each bibliographical unit**.

## Acceptance Criteria
- [ ] AC 1 There is a clickable, functional link at each card in the general view
- [ ] AC 2 change general view template
- [ ] AC 3 change single view template
- [ ] AC 4 all links are functional

## Tasks

- [ ] T1 debug Error 500 / refactor the code to make links functional and 
- [ ] T2 refactor general view templates to include less data in the template
- [ ] T3 refactor single view templates to include more data
- [ ] T4 manual testing and updating Readme.md file
