### ISSUE TITLE
Implement Edit/Delete buttons

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#26]
## User Story
As a **signed user** I can **approach individual bibliographical units and delete/edit my contributions** so that **I can change text or delete it**.

## Acceptance Criteria
- [ ] Delete and Edit buttons exist in each individual bibliography card
- [ ] Delete and Edit buttons are functional
- [ ] 
- [ ] AC 4

## Tasks

- [ ] T1 create and style Delete and Edit buttons in the template
- [ ] T2 create/refactor Delete and Edit functions for these two tasks in the Wiews
- [ ] T3 Test, document the functionality and improve Readme.md file
- [ ] T4
