### ISSUE TITLE
EPIC <Edit/Delete buttons>

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#27]
## User Story
As a **signed author of the bibliography unit** I can **delete/enter my entries** so that **improve/correct the content of my entries**.

## Acceptance Criteria
- [ ] AC 1 Edit/Delete buttons are visible only for logged author of the bibliography unit
- [ ] AC 2 Edit/Delete buttons are functional
- [ ] AC 3
- [ ] AC 4

## Tasks

- [ ] T1 add buttons to single view template and style them
- [ ] T2 add/refactor views to handle the delete/edit functionality
- [ ] T3 test and document functionality
- [ ] T4 improve Readme.md file
