### ISSUE TITLE
USER STORY <debug Error 500>

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#28]
## User Story
As a **user/loged user** I can **see the single view of the individual bibliographical units** so that **read its content OR delete/edit its content**.

## Acceptance Criteria
- [ ] AC 1 link is now clickable and functional
- [ ] AC 2 Readme,md file is updated
- [ ] AC 3
- [ ] AC 4

## Tasks

- [ ] T1 debagge the problem
- [ ] T2 test and document the debugging result
- [ ] T3
- [ ] T4
