### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#3]
## User Story
As a **user** I can **see the favicon in the nav bar** so that **I can navigate tabs more easily**.

## Acceptance Criteria
- [ ] AC 1 favicon is clearly visible in the nav bar
- [ ] AC 2 test the functionality
- [ ] AC 3 
- [ ] AC 4

## Tasks

- [ ] T1 chose appropriate favicon
- [ ] T2 add favicon to code
- [ ] T3 test the functionality
- [ ] T4
