### ISSUE TITLE
Add "Created on" in Review model

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#4]
## User Story
As a **user** I can **see the automatically generated date when my post was created** so that ** I can monitor the temporal component of my activities**.

## Acceptance Criteria
- [x] AC 1 "Created on" is generated and visible in the Review page 
- [ ] AC 2 
- [ ] AC 3
- [ ] AC 4

## Tasks

- [x] T1 change the Review model
- [x] T2 migrate
- [x] T3 test the functionality
- [ ] T4
