### ISSUE TITLE
Add Summernote App

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#5]
## User Story
As a **superuser** I can **use Summernote app** so that **I increase UX and improve data navigability**.

## Acceptance Criteria
- [ ] AC 1 Summernote is installed
- [ ] AC 2 Book app is updated to use Summernote
- [ ] AC 3 Changes in the Admin page are visible
- [ ] AC 4 Functionality of the Summernote is tested

## Tasks

- [ ] T1 install Summernote
- [ ] T2 connect Summernote to the Book app
- [ ] T3 confirm the visibility of the changed Admin page
- [ ] T4 test the functionality of the Summernote
