### ISSUE TITLE
Create Django Generic Views

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#6]
## User Story
As a **role** I can **capability** so that **received benefit**.

## Acceptance Criteria
- [x] AC 1 Django Generic Views are created
- [x] AC 2 Django Generic Views is deployed
- [x] AC 3 Django Generic Views are tested
- [ ] AC 4

## Tasks

- [x] T1 create urls.py files
- [x] T2 include new, string urlpatern
- [x] T3 create template directory and HTML code
- [x] T4 replace function-based view with the class based view
- [x] T5 connect views with the URLs
- [x] T6 deploy the changes 
- [x] T7 test the functionality of the Django Generic Views
