### ISSUE TITLE
Create base template and homepage

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#7]
## User Story
As a **user** I can **land on the review page after visiting the site** so that **I can navigate through the content of that page**.

## Acceptance Criteria
- [x] AC 1 user lands on the review page upon clicking on the website address
- [x] AC 2 HTML and CSS files are created and linked
- [x] AC 3 static files are created and located in "staticfiles" directory
- [x] AC 4 Heroku is prepared for deployment
- [x] AC 5 code is tested and operational

## Tasks

- [x] T1 prepare the project for multiple template directories
- [x] T2 Create basic base.html and index.html templates
- [x] T3 Create style.css file 
- [x] T4 Create static files and remove DISABLE_COLLECTSATIC in HEROKU
- [x] T5 Create runtime.txt. file and set the correct value
- [x] T6 install whitenoise
- [x] T7 test functionality of the code

**Comment by VladaAlek** [comment]
In the next task, adjust the HTML and CSS files to match your project's design
