### ISSUE TITLE
Add excerpt field to the Review page/model

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#8]
## User Story
As a **user** I can **see the excerpt based on the book's title** so that **I can better navigate the page**.

## Acceptance Criteria
- [ ] AC 1 Excerpts are visible on the Review page
- [ ] AC 2 The functionality and practicality of this design is tested
- [ ] AC 3
- [ ] AC 4

## Tasks

- [ ] T1 refactor Review model
- [ ] T2 Migrate model
- [ ] T3 Deploy the changes
- [ ] T4 Test if the excerpts are visible and properly created

**Comment by VladaAlek** [comment]
This issues needs further evaluation.
