### ISSUE TITLE
CREATE CUSTOM CSS

### ISSUE THREAD

**Issue by VladaAlek** [VladaAlek/Django_17_06_24_really_good#9]
## User Story
As a **product owner** I can **see the first version of the custom CSS** so that **I can examine its functionality**.

## Acceptance Criteria
- [ ] AC 1 style.css is created
- [ ] AC 2 style.css is linked to apps
- [ ] AC 3 functionality of style.css is tested
- [ ] AC 4

## Tasks

- [x] T1 create style.css
- [ ] T2 link style.css to HTML files
- [ ] T3 use W3C CSS Validation Service to validate css file
- [ ] T4

**Comment by VladaAlek** [comment]
T2 style css connected only to base.html, not to index.html too
